export const ADD_QUESTIONS = "ADD_QUESTIONS";
export const UPDATE_QUESTION_LOADER = "UPDATE_QUESTION_LOADER";

export const MAKE_CHOICE = "MAKE_CHOICE";
export const DELETE_CHOICE = "DELETE_CHOICE";
export const UPDATE_CHOICE = "UPDATE_CHOICE";
export const SEND_CHOICES_LOADER = "SEND_CHOICES_LOADER";


export const UPDATE_SCORE = "UPDATE_SCORE";
export const RESET_SCORE = "UPDATE_SCORE";
export const ADD_TO_SCORE = "UPDATE_SCORE";
